export async function nextSignal():Promise<void>
export async function previous():Promise<void>
export async function countSignal():Promise<void>
export async function formatSignals():Promise<void>
export async function relatory():Promise<void>
export async function remaining():Promise<void>
export async function executed():Promise<void>
export async function last():Promise<void>
export async function config():Promise<void>
export async function usage():Promise<void>